name: TPP
version: '${version}'
main: top.syshub.tpp.TPP
api-version: '1.20'
load: STARTUP
authors: [ Dainsleif ]
description: A team mini-game tool for Minecraft.
website: mc.syshub.top
commands:
  tpp:
    usage: "/tpp <target>"
  tppconfig:
    usage: "/tppconfig <module> <config> <value>"
    permission: "minecraft.command.teleport"